goal_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session

  resources :goals
  resources :comments 
end

goal_app/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, :user, :commentable, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :user, inverse_of: :comments

  def comment_type
    self.commentable_type
  end
end

goal_app/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  body       :text             not null
#  complete   :boolean          default(FALSE)
#  private    :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base

  validates :user, :body, presence: true
  belongs_to :user

  def private?
    self.private
  end

  def completed?
    self.complete
  end

  has_many :comments, as: :commentable


end

goal_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :goals
  has_many :comments, as: :commentable

  attr_reader :password
  after_initialize :generate_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(32)
    self.save!
    self.session_token
  end

  private
  def generate_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(32)
  end
end

goal_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user, :login, :require_login

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
    @current_user ? @current_user : nil
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_sesion_url unless current_user
  end

end

goal_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end


  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      if @comment.commentable_type == 'user'
        redirect_to user_url(@comment.commentable)
      else
        redirect_to goal_url(@comment.commentable)
      end
      # @comment.comment_type == 'user' ? redirect_to user_url(@comment.commentable) : redirect_to goal_url(@comment.commentable)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end

end

goal_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
  end

  def create
    # debugger
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def index
    @goals = Goal.all
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      render :edit
    end
  end

  def show
    @goal = Goal.find(params[:id])
    @comments = @goal.comments
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_url
  end

  def goal_params
    params.require(:goal).permit(:body)
  end

end

goal_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to goals_url
    else
      flash.now[:errors]  = ['invalid login']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

goal_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to goals_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end



  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goal_app/app/helpers/comments_helper.rb
module CommentsHelper
end

goal_app/app/helpers/goals_helper.rb
module GoalsHelper
end

goal_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

goal_app/app/helpers/users_helper.rb
module UsersHelper
end

goal_app/app/views/comments/_comment.html.erb
<form action="/comments" method="POST">

    <textarea name="comment[body]" id="" cols="30" rows="10"></textarea>
  <input type="hidden" name="comment[commentable_type]" value="<%= comment.class %>">
  <input type="hidden" name="comment[commentable_id]" value="<%= comment.id %>">
    <input type="submit" value="Add Comment">
</form>

goal_app/app/views/goals/index.html.erb
<h>All Goals!</h>
<% @goals.each do |goal| %>
  <% unless goal.private? %>
    <a href="/goals/<%= goal.id %>"><%= goal.body %></a>
  <% end %>
<% end %>

<%= link_to "Add Goal", new_goal_url %>

goal_app/app/views/goals/new.html.erb
Submit Goal
<form action="/goals" method="POST">

  <label>Body:
    <textarea name="goal[body]" cols="30" rows="10"></textarea>
  </label>

  <input type="submit" value="Submit Goal">
</form>

goal_app/app/views/goals/show.html.erb
<h1>GOAL: <%= @goal.body %> </h1>
<h2>USERNAME: <%= @goal.user.username %> </h2>
<% @comments.each do |comment| %>
  <%= comment.body %>
  <%= comment.user.username %>
<% end %>
<%= render "comments/comment", comment: @goal %>

goal_app/app/views/users/new.html.erb
<h>Sign Up</h>

<form action="<%= users_url %>" method='POST'>
<input type="hidden" name='authenticity_token' value='<%= form_authenticity_token %>'>

  <label>Username
    <input type="text" name='user[username]'>
  </label>

  <label>Password
    <input type="password" name='user[password]'>
  </label>

  <input type="submit" value='Create User'>
</form>