todo_lists/config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :users
  resource :session

  resources :goals
  resources :comments 
=======
  namespace :api, default: {format: :json} do
    resources :todos, only: [:index, :create, :update, :destroy]
  end

  root to: 'static_pages#root'
>>>>>>> old_i/master
end

todo_lists/app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :body, :title, presence: true
end

todo_lists/app/controllers/api/todos_controller.rb
class Api::TodosController < ApplicationController
  def index
    render json: Todo.all
  end

  def create
    @todo_list = Todo.create(todo_params)
    render json: @todo_list
  end

  def update

  end

  def destroy

  end

  private
  def todo_params
    params.require(:todo).permit(:title, :body)
  end
end

todo_lists/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
<<<<<<< HEAD
  # protect_from_forgery with: :exception

  helper_method :current_user, :login, :require_login

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
    @current_user ? @current_user : nil
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_sesion_url unless current_user
  end

=======
  protect_from_forgery with: :exception
>>>>>>> old_i/master
end

todo_lists/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
    render :root
  end
end

todo_lists/app/helpers/api/todos_helper.rb
module Api::TodosHelper
end

todo_lists/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<<<<<<< HEAD
  <title>Motivator</title>
=======
  <title>ReduxTodo</title>
>>>>>>> old_i/master
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<<<<<<< HEAD

  <% flash[:errors].try(:each) do |error| %>
    <%= error %>
  <% end %>


<% if current_user %>
  <%= current_user.username %>
  <%= button_to 'Log Out', session_url(current_user), method: :delete %>
<% else %>
  <%= link_to 'Login', new_session_url %>
  <%= link_to 'Sign Up', new_user_url %>
<% end %>

=======
>>>>>>> old_i/master
<%= yield %>

</body>
</html>

todo_lists/app/views/static_pages/root.html.erb
<div id="content">

</div>